apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-bun-config
data:
  bun-load-test.js: |
    import http from "k6/http";
    import { check, group, sleep } from "k6";
    import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

    export let options = {
      stages: [
        { duration: "10s", target: 500 }, // 1 phút, 50 người dùng
        { duration: "1m", target: 2000 }, // 2 phút, tăng lên 500 người dùng
        { duration: "1m", target: 1000 }, // 1 phút, giảm về 50 người dùng
        { duration: "10s", target: 0 }, // 1 phút, giảm về 0 người dùng
      ],
    };

    export default function () {
      let baseUrl = __ENV.BASE_URL;

      group("Load test group", () => {
        // Tạo mới một resource
        let res = http.post(
          `${baseUrl}/api/posts`,
          JSON.stringify({
            title: "First Post",
            content: "The first post made",
          }),
          {
            headers: {
              "Content-Type": "application/json",
            },
            tags: { name: "CreateResource" },
          }
        );
        check(res, {
          "status is 200": (r) => r.status === 200,
          "resource created": (r) => r.json("id") !== "",
        });
        let resourceId = res.json("id");
        sleep(1);

        // Xem chi tiết resource
        res = http.get(`${baseUrl}/api/posts/${resourceId}`, {
          tags: { type: "GetResource" },
        });
        check(res, {
          "status is 200": (r) => r.status === 200,
          "resource id matches": (r) => r.json("id") === resourceId,
        });
        sleep(1);

        // Cập nhật resource
        res = http.patch(
          `${baseUrl}/api/posts/${resourceId}`,
          JSON.stringify({
            title: "Updated Resource",
            content: "Updated value",
          }),
          {
            headers: {
              "Content-Type": "application/json",
            },
            tags: { name: "UpdateResource" },
          }
        );
        check(res, {
          "status is 200": (r) => r.status === 200,
          "resource updated": (r) => r.json("title") === "Updated Resource",
        });
        sleep(1);

        // Xóa resource
        res = http.del(
          `${baseUrl}/api/posts`,
          JSON.stringify({
            id: resourceId,
          }),
          {
            headers: {
              "Content-Type": "application/json",
            },
            tags: { name: "UpdateResource" },
          }
        );
        check(res, {
          "status is 200": (r) => r.status === 200,
          "resource delete": (r) => r.json("id") !== "", 
        });
        sleep(1);
      });
    }

    export function handleSummary(data) {
      return {
        "/report/summary.html": htmlReport(data),
      };
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: k6-bun
spec:
  restartPolicy: Never
  containers:
    - name: k6
      image: loadimpact/k6
      env:
        - name: BASE_URL
          value: "http://bunjs.default.svc.cluster.local:3000"
      command: 
        - "/bin/sh"
        - "-c"
        - |
          apk update && apk --no-cache add curl && \
          k6 run /performace_testing_script/bun-load-test.js && \
          curl -F "chat_id=-4288739311" \
               -F 'media=[{"type": "document", "media": "attach://file1"}]' \
               -F "file1=@/report/summary.html" \
               "https://api.telegram.org/${BOT_ID}:${BOT_TOKEN}/sendMediaGroup"
      resources: {}
      volumeMounts:
        - name: k6-script-volume
          mountPath: /performace_testing_script
        - name: writable-volume
          mountPath: /report
      securityContext:
        runAsUser: 0  # run với user root
        runAsGroup: 0 
  volumes:
    - name: k6-script-volume
      configMap:
        name: k6-bun-config
    - name: writable-volume
      emptyDir: {}